version: '3.8'

services:
  app:
    build:
      context: "."
      dockerfile: "Dockerfile"
    env_file:
      - ".env"
    command: >
      bash -c "python manage.py migrate
      && python manage.py initadmin
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    networks:
      - "app"
    restart: "always"
    depends_on:
      - "db"

  db:
    image: "postgres:alpine"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ".env"
    restart: "always"
    networks:
      - "app"

networks:
  app:
    driver: "bridge"

volumes:
  db_data:
