version: '3.7'

services:
  app:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    env_file:
      - ".env"
    command: >
      bash -c "python manage.py migrate
      && python manage.py initadmin
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - "app"
      - "db"
      - "outside"
    restart: "always"
    depends_on:
      - "db"

  db:
    image: "postgres:10-alpine"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    env_file:
      - ".env"
    restart: "always"
    networks:
      - "db"

networks:
  outside:
    external: true
  db:
    driver: "bridge"
  app:
    driver: "bridge"

volumes:
  db-data: