# Generated by Django 2.1.12 on 2019-09-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Основные', 'verbose_name_plural': 'Настройки'},
        ),
    ]
