# Generated by Django 2.1.12 on 2019-09-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databases',
            name='driver',
            field=models.CharField(choices=[('{ODBC Driver 17 for SQL Server}', 'ODBC Driver 17 for SQL Server'), ('{ODBC Driver 13 for SQL Server}', 'ODBC Driver 13 for SQL Server'), ('{ODBC Driver 11 for SQL Server}', 'ODBC Driver 11 for SQL Server'), ('{SQL Server}', 'SQL Server (Windows)')], default='{ODBC Driver 17 for SQL Server}', max_length=50, verbose_name='Драйвер'),
        ),
    ]
