# Generated by Django 3.0.5 on 2020-04-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20190929_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Объект <django.db.models.fields.AutoField>', max_length=254, verbose_name='Отображаемое имя')),
                ('database', models.CharField(max_length=254, verbose_name='Имя базы данных')),
                ('server', models.CharField(max_length=254, verbose_name='Сервер')),
                ('user', models.CharField(max_length=254, verbose_name='Имя пользователя')),
                ('pwd', models.CharField(max_length=254, verbose_name='Пароль')),
                ('driver', models.CharField(choices=[('{ODBC Driver 17 for SQL Server}', 'ODBC Driver 17 for SQL Server'), ('{ODBC Driver 13 for SQL Server}', 'ODBC Driver 13 for SQL Server'), ('{ODBC Driver 11 for SQL Server}', 'ODBC Driver 11 for SQL Server'), ('{SQL Server}', 'SQL Server (Windows)')], default='{ODBC Driver 17 for SQL Server}', max_length=50, verbose_name='Драйвер')),
                ('type', models.CharField(choices=[('', 'Не используется'), ('aqua', 'База аквапарка'), ('beach', 'База пляжа'), ('bitrix', 'База Bitrix')], default='', max_length=50, verbose_name='Соответствие')),
                ('is_have_zones', models.BooleanField(default=False, verbose_name='Есть зоны')),
                ('is_display_sum', models.BooleanField(default=False, verbose_name='Показывать сумму')),
            ],
            options={
                'verbose_name': 'базу данных',
                'verbose_name_plural': 'Базы данных',
            },
        ),
        migrations.RenameModel(
            old_name='TariffList',
            new_name='Tariff',
        ),
        migrations.AlterField(
            model_name='settingbase',
            name='db_aqua',
            field=models.ForeignKey(help_text='Значение из списка раздела "Базы данных"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aqua', to='settings.DataBase', verbose_name='БД Bars-Аквапарк'),
        ),
        migrations.AlterField(
            model_name='settingbase',
            name='db_beach',
            field=models.ForeignKey(help_text='Значение из списка раздела "Базы данных"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beach', to='settings.DataBase', verbose_name='БД Bars-Пляж'),
        ),
        migrations.AlterField(
            model_name='settingbase',
            name='db_bitrix',
            field=models.ForeignKey(help_text='Значение из списка раздела "Базы данных"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitrix', to='settings.DataBase', verbose_name='БД Bitrix'),
        ),
        migrations.DeleteModel(
            name='DataBases',
        ),
    ]
