# Generated by Django 2.1.12 on 2019-09-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20190928_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Название используется в шаблонах оформления.', max_length=128, verbose_name='Название компании')),
                ('company_address', models.CharField(help_text='Кратко и доходчиво, пожалуйста.', max_length=256, verbose_name='Адрес')),
                ('company_email', models.CharField(help_text='Эл. адрес для обращения за консультациями.', max_length=128, verbose_name='Эл. адрес')),
                ('company_schedule', models.TextField(help_text='Полезно добавлять информацию о работе в праздничные дни.', verbose_name='График работы')),
                ('company_description', models.TextField(help_text='Краткое описание компании. Может использоваться в небольшом блоке.', verbose_name='О компании')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
    ]
