# Generated by Django 2.1.12 on 2019-09-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20190928_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='company_name',
        ),
        migrations.AddField(
            model_name='setting',
            name='db_aqua',
            field=models.PositiveIntegerField(blank=True, help_text='Числовой id из списка баз данных в разделе "Базы данных"', null=True, verbose_name='ID базы данных Bars - Аквапарк'),
        ),
        migrations.AddField(
            model_name='setting',
            name='db_beach',
            field=models.PositiveIntegerField(blank=True, help_text='Числовой id из списка баз данных в разделе "Базы данных"', null=True, verbose_name='ID базы данных Bars - Пляж'),
        ),
        migrations.AddField(
            model_name='setting',
            name='db_site',
            field=models.PositiveIntegerField(blank=True, help_text='Числовой id из списка баз данных в разделе "Базы данных"', null=True, verbose_name='ID базы данных копии заказов с сайта'),
        ),
    ]
