# Generated by Django 3.0.5 on 2020-04-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20200426_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='port',
            field=models.CharField(default='1433', max_length=10, verbose_name='Порт'),
        ),
        migrations.AlterField(
            model_name='database',
            name='title',
            field=models.CharField(default='Объект', max_length=254, verbose_name='Отображаемое имя'),
        ),
        migrations.AlterField(
            model_name='database',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Не используется'), ('aqua', 'База аквапарка'), ('beach', 'База пляжа'), ('bitrix', 'База Bitrix')], default='', max_length=50, verbose_name='Соответствие'),
        ),
        migrations.DeleteModel(
            name='SettingBase',
        ),
    ]
