# Generated by Django 2.1.12 on 2019-09-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20190928_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_aqua', models.PositiveIntegerField(blank=True, help_text='Числовой id из списка баз данных в разделе "Базы данных"', null=True, verbose_name='ID БД Bars-Аквапарк')),
                ('db_beach', models.PositiveIntegerField(blank=True, help_text='Числовой id из списка баз данных в разделе "Базы данных"', null=True, verbose_name='ID БД Bars-Пляж')),
                ('db_bitrix', models.PositiveIntegerField(blank=True, help_text='Числовой id из списка баз данных в разделе "Базы данных"', null=True, verbose_name='ID БД заказов с сайта')),
            ],
            options={
                'verbose_name': 'Сопоставление баз данных',
                'verbose_name_plural': 'Сопоставление баз данных',
            },
        ),
        migrations.CreateModel(
            name='SettingBitrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(help_text='Адрес сайта без "http://" и "/", например "exsample.com"', null=True, verbose_name='Адрес сайта')),
                ('path', models.CharField(default='/bitrix/admin/1c_exchange.php', help_text='Путь к обработчику 1С на сайте', max_length=255, verbose_name='Путь к обработчику 1С')),
                ('login', models.CharField(help_text='Логин админки bitrix', max_length=255, null=True, verbose_name='Логин')),
                ('password', models.CharField(help_text='Пароль админки bitrix', max_length=255, null=True, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Настройки Bitrix',
                'verbose_name_plural': 'Настройки Bitrix',
            },
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
