# Generated by Django 2.1.12 on 2019-09-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20190928_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingbase',
            options={'verbose_name': 'Сопоставление баз данных', 'verbose_name_plural': 'сопоставление баз данных'},
        ),
        migrations.AlterModelOptions(
            name='settingbitrix',
            options={'verbose_name': 'Настройки Bitrix', 'verbose_name_plural': 'настройки подключения к сайту Bitrix'},
        ),
    ]
