# Generated by Django 2.1.12 on 2019-09-28 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20190929_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=254, verbose_name='Имя базы данных')),
                ('server', models.CharField(max_length=254, verbose_name='Сервер')),
                ('user', models.CharField(max_length=254, verbose_name='Имя пользователя')),
                ('pwd', models.CharField(max_length=254, verbose_name='Пароль')),
                ('driver', models.CharField(max_length=254, verbose_name='Драйвер')),
                ('title', models.CharField(default='Объект 1', max_length=254, verbose_name='Отображаемое имя')),
                ('get_count_clients', models.BooleanField(default=False, verbose_name='Есть зоны')),
                ('get_total_sum', models.BooleanField(default=False, verbose_name='Показывать сумму')),
            ],
            options={
                'verbose_name': 'базу данных',
                'verbose_name_plural': 'Базы данных',
            },
        ),
        migrations.CreateModel(
            name='FinanceReportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'категорию финансового отчета',
                'verbose_name_plural': 'Категории финансового отчета',
            },
        ),
        migrations.CreateModel(
            name='PayAgentReportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'категорию отчета платежного агента',
                'verbose_name_plural': 'Категории отчета платежного агента',
            },
        ),
        migrations.CreateModel(
            name='TariffList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Тариф')),
                ('finance_report_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.FinanceReportCategory', verbose_name='Категория финансового отчета')),
                ('pay_agent_report_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.PayAgentReportCategory', verbose_name='Категория отчета платежного агента')),
            ],
            options={
                'verbose_name': 'тариф',
                'verbose_name_plural': 'Список тарифов',
            },
        ),
    ]
