# Generated by Django 2.1.12 on 2019-09-29 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_databases_financereportcategory_payagentreportcategory_tarifflist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingbase',
            name='db_aqua',
            field=models.ForeignKey(help_text='Значение из списка раздела "Базы данных"', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.DataBases', verbose_name='ID БД Bars-Аквапарк'),
        ),
    ]
