# Generated by Django 2.1.12 on 2019-09-29 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_20190929_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingbase',
            name='db_beach',
        ),
        migrations.RemoveField(
            model_name='settingbase',
            name='db_bitrix',
        ),
        migrations.AlterField(
            model_name='settingbase',
            name='db_aqua',
            field=models.ForeignKey(help_text='Значение из списка раздела "Базы данных"', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.DataBases', verbose_name='БД Bars-Аквапарк'),
        ),
    ]
