# Generated by Django 2.1.12 on 2019-09-29 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_auto_20190929_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingbase',
            name='db_beach',
            field=models.ForeignKey(help_text='Значение из списка раздела "Базы данных"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beach', to='settings.DataBases', verbose_name='БД Bars-Пляж'),
        ),
        migrations.AddField(
            model_name='settingbase',
            name='db_bitrix',
            field=models.ForeignKey(help_text='Значение из списка раздела "Базы данных"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitrix', to='settings.DataBases', verbose_name='БД Bitrix'),
        ),
        migrations.AlterField(
            model_name='settingbase',
            name='db_aqua',
            field=models.ForeignKey(help_text='Значение из списка раздела "Базы данных"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aqua', to='settings.DataBases', verbose_name='БД Bars-Аквапарк'),
        ),
    ]
