# Generated by Django 2.1.12 on 2019-09-28 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('request_date', models.DateTimeField(default=datetime.datetime(2019, 9, 28, 17, 49, 49, 647061), verbose_name='Дата создания')),
                ('time_type', models.CharField(max_length=254, verbose_name='Временной тип')),
                ('date_from', models.DateTimeField(verbose_name='Начало периода')),
                ('date_to', models.DateTimeField(verbose_name='Конец периода')),
                ('data', models.TextField(verbose_name='Данные отчета в JSON')),
                ('author', models.CharField(max_length=100, verbose_name='Инициатор запроса')),
            ],
            options={
                'verbose_name': 'запись отчета',
                'verbose_name_plural': 'Записи отчетов',
            },
        ),
    ]
