# Generated by Django 2.1.12 on 2019-09-28 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190928_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 17, 55, 9, 338384), verbose_name='Дата создания'),
        ),
    ]
