# Generated by Django 2.1.12 on 2019-09-28 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20190928_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 17, 56, 49, 769785), verbose_name='Дата создания'),
        ),
    ]
