# Generated by Django 2.1.12 on 2019-09-28 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20190928_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 19, 2, 56, 757967), verbose_name='Дата создания'),
        ),
    ]
