# Generated by Django 2.1.12 on 2019-09-28 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20190928_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 19, 5, 10, 779643), verbose_name='Дата создания'),
        ),
    ]
