# Generated by Django 2.1.12 on 2019-09-28 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20190928_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 19, 6, 41, 947953), verbose_name='Дата создания'),
        ),
    ]
