# Generated by Django 2.1.12 on 2019-09-28 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20190928_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 21, 7, 17, 574593), verbose_name='Дата создания'),
        ),
    ]
