# Generated by Django 2.1.12 on 2019-09-28 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20190929_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 21, 9, 40, 875320), verbose_name='Дата создания'),
        ),
    ]
