# Generated by Django 2.1.12 on 2019-09-28 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20190929_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 21, 37, 43, 639673), verbose_name='Дата создания'),
        ),
    ]
