# Generated by Django 2.1.12 on 2019-09-28 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_auto_20190929_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 21, 48, 7, 610581), verbose_name='Дата создания'),
        ),
    ]
