# Generated by Django 2.1.12 on 2019-09-29 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_auto_20190929_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 9, 49, 50, 923169), verbose_name='Дата создания'),
        ),
    ]
