# Generated by Django 2.1.12 on 2019-09-29 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_auto_20190929_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 9, 53, 56, 825035), verbose_name='Дата создания'),
        ),
    ]
