# Generated by Django 2.1.12 on 2019-09-29 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_auto_20190929_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 9, 56, 7, 854859), verbose_name='Дата создания'),
        ),
    ]
